import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  topHeaderSection: {
    width: width,
    height: height * 0.40,
    position: "relative",
    justifyContent: "flex-end",
    paddingBottom: height * 0.095,
  },
  backgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: width,
    height: "100%",
  },
  gradientOverlay: {
    ...StyleSheet.absoluteFillObject,
    width: width,
    height: "100%",
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: width * 0.06,
    paddingTop: Platform.OS === "ios" ? 0 : 16,
  },
  roundButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(20, 20, 20, 0.3)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.4)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  headerTitle: {
    fontSize: width > 360 ? 32 : 26,
    fontWeight: "bold",
    color: "#FFF",
    paddingHorizontal: width * 0.07,
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 6,
  },
  emptyView: {
    width: 44,
  },
  infoBottomSection: {
    flex: 1,
    backgroundColor: "#0A0A0A",
    marginTop: -height * 0.08,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    paddingHorizontal: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 12,
  },
  scrollContent: {
    paddingTop: 24,
    paddingBottom: 20,
    paddingHorizontal: width * 0.07,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: "#161616",
    borderRadius: 16,
    padding: 14,
    marginBottom: 20,
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 4,
  },
  selectContainerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inputSearchContainer: {
    position: "relative",
    width: "100%",
    marginBottom: 20,
  },
  inputSpinner: {
    position: "absolute",
    right: 16,
    top: 14,
    zIndex: 5,
  },
  textInputField: {
    backgroundColor: "#161616",
    borderRadius: 16,
    padding: 14,
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "500",
    paddingRight: 45,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 4,
  },
  autocompleteContainer: {
    backgroundColor: "#161616",
    borderRadius: 16,
    marginTop: -15,
    marginBottom: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 5,
  },
  autocompleteItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    flexDirection: "row",
    alignItems: "center",
  },
  autocompleteText: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "500",
    flex: 1,
  },
  inputText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "500",
    flex: 1,
  },
  rowInputs: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 12,
  },
  inputCol: {
    flex: 1,
  },
  labelCol: {
    fontSize: 12,
    fontWeight: "700",
    color: "#9E9E9E",
    marginBottom: 8,
    textAlign: "center",
    textTransform: "uppercase",
  },
  inputCenter: {
    backgroundColor: "#161616",
    borderRadius: 16,
    padding: 12,
    textAlign: "center",
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 5,
    elevation: 4,
  },
  ticketCard: {
    backgroundColor: "#161616",
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    marginHorizontal: 3,
    marginVertical: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
    elevation: 6,
  },
  companyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  companyInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  companyLogoPlaceholder: {
    width: 24,
    height: 24,
    borderRadius: 6,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  companyText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  companyName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  stopsBadge: {
    fontSize: 11,
    color: "#4CAF50",
    backgroundColor: "rgba(76, 175, 80, 0.15)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    fontWeight: "600",
  },
  flightRoute: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  flightInfo: {
    flexDirection: "column",
    width: 75,
  },
  flightTime: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  flightLabel: {
    fontSize: 12,
    color: "#8E9E99",
    marginTop: 2,
  },
  routeLineContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  routeLine: {
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    width: "100%",
    height: 1.5,
  },
  flightReturnRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    paddingTop: 16,
  },
  ticketCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    paddingTop: 12,
  },
  cardPriceLabel: {
    fontSize: 12,
    color: "#8E9E99",
    fontWeight: "500",
  },
  cardPriceValue: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  cardSelectButton: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 0,
    borderColor: "transparent",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  cardSelectButtonText: {
    color: "#FFF",
    fontSize: 13,
    fontWeight: "700",
  },
  classBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  classBadgeText: {
    fontSize: 11,
    fontWeight: "700",
  },
  flightRouteRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  routeCol: {
    alignItems: "center",
  },
  routeTime: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  routeAirport: {
    fontSize: 12,
    color: "#A0B0AD",
    fontWeight: "600",
    marginTop: 2,
  },
  routeMiddle: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 12,
  },
  durationText: {
    fontSize: 11,
    color: "#8E9E99",
    fontWeight: "500",
    marginBottom: 4,
  },
  flightLineContainer: {
    width: "100%",
    alignItems: "center",
    position: "relative",
    justifyContent: "center",
  },
  flightLine: {
    width: "100%",
    height: 1.5,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
  },
  planeIconWrap: {
    position: "absolute",
    backgroundColor: "#161616",
    paddingHorizontal: 4,
  },
  stopsText: {
    fontSize: 10,
    fontWeight: "600",
    marginTop: 4,
  },
  ticketFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 14,
    marginTop: 4,
  },
  datesInfo: {
    flex: 1,
  },
  dateText: {
    fontSize: 11,
    color: "#9E9E9E",
    fontWeight: "500",
    marginBottom: 2,
  },
  ticketPriceWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  ticketPrice: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  footerPriceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: width * 0.07,
    backgroundColor: "#0A0A0A",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  priceContainer: {
    justifyContent: "center",
    flex: 1,
    paddingRight: 10,
  },
  priceLabel: {
    fontSize: 12,
    color: "#9E9E9E",
    fontWeight: "500",
  },
  priceValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
    marginTop: 1,
  },
  actionButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 40,
  },
  loadingText: {
    marginTop: 12,
    color: "#9E9E9E",
    fontSize: 15,
    fontWeight: "500",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 40,
  },
  errorText: {
    color: "#FF5252",
    textAlign: "center",
    marginBottom: 15,
    fontSize: 15,
    fontWeight: "600",
  },
  retryButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: "#1C1C1E",
    borderRadius: 14,
  },
  retryButtonText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  modalOverlay: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0,0,0,0.75)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: width * 0.90,
    backgroundColor: "rgba(0, 0, 0, 0.94)",
    borderRadius: 24,
    padding: 20,
    borderWidth: 0,
    borderColor: "transparent",
  },
  modalDestinationContent: {
    width: width * 0.90,
    maxHeight: height * 0.50,
    backgroundColor: "rgba(0, 0, 0, 0.94)",
    borderRadius: 24,
    padding: 20,
    borderWidth: 0,
    borderColor: "transparent",
  },
  calendarSelectorRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingHorizontal: 5,
  },
  calendarTitleText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  calendarNavButton: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    padding: 10,
    borderRadius: 12,
  },
  calendarHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  calendarHeaderCell: {
    width: "14.28%",
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
    color: "#9E9E9E",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-start",
  },
  calendarDay: {
    width: "14.28%",
    aspectRatio: 1,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 4,
  },
  calendarDayActive: {
    borderRadius: 12,
  },
  calendarDayText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  calendarDayTextActive: {
    color: "#000000",
    fontWeight: "800",
  },
  calendarDayTextDisabled: {
    color: "rgba(255, 255, 255, 0.2)",
  },
  calendarDayTextEmpty: {
    color: "transparent",
  },
  closeModalButton: {
    marginTop: 15,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    padding: 14,
    borderRadius: 16,
    alignItems: "center",
  },
  closeModalButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 15,
  },
  flex1: {
    flex: 1,
  },
  marginRight8: {
    marginRight: 8,
  },
  marginRight10: {
    marginRight: 10,
  },
  marginRight6: {
    marginRight: 6,
  },
  marginRight4: {
    marginRight: 4,
  },
  marginBottom12: {
    marginBottom: 12,
  },
  marginTop10Bottom2: {
    marginTop: 10,
    marginBottom: 2,
  },
  rowCenterMarginBottom4: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
  },
  companyLogo: {
    width: 24,
    height: 24,
    resizeMode: "contain",
    marginRight: 6,
  },
  flightDetailTextDark: {
    fontSize: 12,
    color: "#8E8E93",
  },
  flightDetailTextLight: {
    fontSize: 12,
    color: "#4B5563",
  },
  ticketCardLight: {
    backgroundColor: "#FFFFFF",
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
});
