import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");
const STRICT_THUMB_SIZE = Math.round(width * 0.115);

export default StyleSheet.create({
  mainContainer: {
    flex: 1,
  },
  containerLight: {
    backgroundColor: "#FFFFFF",
  },
  containerDark: {
    backgroundColor: "#000000",
  },
  imageSection: {
    width: width,
    height: height * 0.52,
    position: "relative",
  },
  mainImageTouchable: {
    width: "100%",
    height: "100%",
  },
  mainImage: {
    width: "100%",
    height: "100%",
  },
  mainImageEmpty: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  mainImageEmptyDark: {
    backgroundColor: "#141414",
  },
  mainImageEmptyLight: {
    backgroundColor: "#222222",
  },
  emptyImageText: {
    color: "rgba(255, 255, 255, 0.6)",
    marginTop: 12,
    fontSize: 15,
    fontWeight: "500",
  },
  topBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 9999,
    elevation: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: width * 0.06,
    paddingTop: Platform.OS === "ios" ? 0 : 16,
  },
  roundButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(20, 20, 20, 0.3)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    justifyContent: "center",
    alignItems: "center",
    boxShadow: "0 4px 14px rgba(0, 0, 0, 0.4)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 0,
    zIndex: 10000,
  },
  roundButtonLight: {
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    shadowColor: "#000",
    shadowOpacity: 0.1,
  },
  roundButtonDark: {
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  rightActionsColumn: {
    flexDirection: "column",
    alignItems: "center",
    zIndex: 10000,
    elevation: 0,
  },
  rightThumbnails: {
    flexDirection: "column",
    alignItems: "center",
    marginTop: 10,
    gap: 6,
    zIndex: 10000,
    elevation: 0,
  },
  thumbTouch: {
    width: STRICT_THUMB_SIZE,
    height: STRICT_THUMB_SIZE,
    borderRadius: STRICT_THUMB_SIZE / 4,
    overflow: "hidden",
    borderWidth: 2,
    backgroundColor: "rgba(18, 18, 18, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 0,
  },
  thumbImage: {
    width: "100%",
    height: "100%",
  },
  thumbLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(18, 18, 18, 0.75)",
    justifyContent: "center",
    alignItems: "center",
  },
  titleOverlay: {
    position: "absolute",
    bottom: height * 0.105,
    left: width * 0.07,
    right: width * 0.25,
  },
  mainTitle: {
    fontSize: width > 360 ? 32 : 26,
    fontWeight: "bold",
    color: "#FFF",
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 6,
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
  },
  locationText: {
    fontSize: width > 360 ? 15 : 13,
    color: "#FFFFFF",
    marginLeft: 5,
    fontWeight: "500",
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  infoBottomSection: {
    flex: 1,
    backgroundColor: "#0A0A0A",
    marginTop: -height * 0.085,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    paddingHorizontal: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 0,
  },
  infoBottomSectionLight: {
    shadowOpacity: 0.08,
    shadowRadius: 16,
  },
  infoBottomSectionDark: {
    shadowOpacity: 0.6,
    shadowRadius: 16,
  },
  scrollContent: {
    paddingTop: 24,
    paddingBottom: 20,
    paddingHorizontal: width * 0.07,
  },
  scrollContentDetails: {
    paddingTop: 16,
    paddingBottom: 24,
    paddingHorizontal: width * 0.07,
  },
  weatherNotice: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.48)",
    fontStyle: "italic",
    marginBottom: 0,
    fontWeight: "400",
  },
  weatherNoticeTextLight: {
    color: "#6B7280",
    fontSize: 11,
  },
  weatherNoticeTextDark: {
    color: "rgba(255, 255, 255, 0.55)",
    fontSize: 11,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
    gap: 10,
  },
  statsContainerHasWeather: {
    marginBottom: 0,
  },
  statCard: {
    flex: 1,
    height: 72,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#161616",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 7,
    elevation: 0,
  },
  statCardLight: {
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
    elevation: 0,
  },
  statCardDark: {
    borderWidth: 0,
    borderColor: "transparent",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 0,
  },
  statLabel: {
    fontSize: 11,
    color: "#FFFFFF",
    fontWeight: "700",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  statLabelLight: {
    color: "#6B7280",
  },
  statValue: {
    fontSize: 14,
    fontWeight: "bold",
  },
  descriptionHeader: {
    fontSize: 19,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 8,
    includeFontPadding: false,
  },
  descriptionHeaderLight: {
    color: "#111827",
  },
  descriptionHeaderFlex: {
    marginBottom: 0,
    flex: 1,
  },
  descriptionBody: {
    fontSize: 14,
    color: "#e7e7e7",
    lineHeight: 22,
    textAlign: "left",
  },
  descriptionBodyLight: {
    color: "#374151",
  },
  descriptionBodyMargin: {
    marginTop: 12,
  },
  seeMoreText: {
    fontWeight: "700",
  },
  seeMoreTextMargin: {
    fontWeight: "700",
    marginTop: 8,
  },
  aiLoader: {
    alignSelf: "flex-start",
    marginTop: 8,
    marginBottom: 8,
  },
  weatherAlert: {
    fontSize: 12,
    color: "#FFFFFF",
    marginTop: 12,
    fontStyle: "italic",
    lineHeight: 18,
  },
  weatherAlertLight: {
    marginTop: 24,
    marginBottom: 0,
    color: "#6B7280",
    fontStyle: "italic",
  },
  weatherAlertDark: {
    marginTop: 24,
    marginBottom: 0,
    color: "rgba(255, 255, 255, 0.62)",
    fontStyle: "italic",
  },
  footerPriceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 16,
    paddingBottom: 28,
    paddingHorizontal: width * 0.07,
    backgroundColor: "#0A0A0A",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 0,
  },
  footerPriceRowLight: {
    borderTopColor: "rgba(0, 0, 0, 0.08)",
    shadowOpacity: 0.05,
  },
  footerPriceRowDark: {
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    shadowOpacity: 0.4,
  },
  priceContainer: {
    justifyContent: "center",
  },
  priceHelpTouchable: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  priceHelpIcon: {
    marginTop: -1,
  },
  priceSkeletonWrapper: {
    marginTop: 5,
    marginBottom: 2,
  },
  priceLabel: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "600",
    marginBottom: 3,
  },
  priceLabelLight: {
    color: "#6B7280",
  },
  priceValue: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
    marginTop: 1,
  },
  priceValueLight: {
    color: "#111827",
  },
  actionButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    justifyContent: "center",
    alignItems: "center",
    elevation: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
  },
  actionButtonLight: {
    backgroundColor: "#000000",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 0,
  },
  actionButtonIcon: {
    width: 26,
    height: 26,
  },
  actionButtonIconLight: {
    tintColor: "#FFFFFF",
  },
  actionButtonIconDark: {
    tintColor: "#000000",
  },
  fullImageModalOverlay: {
    flex: 1,
    width: width,
    height: height,
    backgroundColor: "rgba(0, 0, 0, 0.88)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalSlide: {
    width: width,
    height: height,
    justifyContent: "center",
    alignItems: "center",
  },
  backdropTouchArea: {
    ...StyleSheet.absoluteFillObject,
  },
  modalImageWrapper: {
    width: width * 0.90,
    height: height * 0.58,
    borderRadius: 24,
    backgroundColor: "rgba(10, 10, 10, 0.65)",
    borderWidth: 0,
    borderColor: "transparent",
    overflow: "hidden",
  },
  modalImageInner: {
    width: "100%",
    height: "100%",
    borderRadius: 24,
    overflow: "hidden",
    position: "relative",
  },
  fullImage: {
    width: "100%",
    height: "100%",
  },
  closeFullImageBtn: {
    position: "absolute",
    top: 14,
    right: 14,
    zIndex: 10,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.45,
    shadowRadius: 5,
    elevation: 6,
  },
  modalCounterBadge: {
    position: "absolute",
    bottom: 14,
    alignSelf: "center",
    zIndex: 10,
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.45,
    shadowRadius: 5,
    elevation: 6,
  },
  modalCounterText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  marginRight8: {
    marginRight: 8,
  },
  marginRight4: {
    marginRight: 4,
  },
  marginRight2: {
    marginRight: 2,
  },
  marginBottom24: {
    marginBottom: 24,
  },
  marginTop24: {
    marginTop: 24,
  },
  rowSpaceBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
  },
  weatherCenterMargin: {
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 6,
    marginTop: 4,
  },
  rowCenterMarginBottom8: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  rowWrap: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  fullScreenCover: {
    width: width,
    height: height,
  },
  fullWidthFlex: {
    width: "100%",
    flex: 1,
  },
  galleryRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    height: height * 0.58,
  },
  flex1FullHeight: {
    flex: 1,
    height: "100%",
  },
  weatherNoticeWrapper: {
    overflow: "hidden",
  },
  alignItemsCenter: {
    alignItems: "center",
  },
});
