export const ENV = {
  API_URL: process.env.EXPO_PUBLIC_API_URL,
  PEXELS_API_KEY: process.env.EXPO_PUBLIC_PEXELS_API_KEY,
  WEATHER_API_KEY: process.env.EXPO_PUBLIC_WEATHER_API_KEY,
  GEMINI_API_KEY: process.env.EXPO_PUBLIC_GEMINI_API_KEY,
  RAPIDAPI_KEY: process.env.EXPO_PUBLIC_RAPIDAPI_KEY,
};
