import { StyleSheet, Dimensions, Platform } from "react-native";

const { width: winW, height: winH } = Dimensions.get("window");
const { width: scrW, height: scrH } = Dimensions.get("screen");
const width = Math.max(winW, scrW);
const height = Math.max(winH, scrH) + (Platform.OS === "android" ? 120 : 0);

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
    overflow: "hidden",
  },
  background: {
    width: width,
    height: height,
    position: "absolute",
    top: 0,
    left: 0,
    transform: [{ scale: 1.08 }],
  },
  overlay: {
    width: width,
    height: height,
    position: "absolute",
    top: 0,
    left: 0,
    backgroundColor: "rgba(0, 0, 0, 0.45)",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 22,
    paddingTop: Platform.OS === "android" ? 36 : 20,
    paddingBottom: 36,
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 26,
  },
  cardWrapper: {
    width: "100%",
    maxWidth: 420,
    alignItems: "center",
  },
  card: {
    width: "100%",
    backgroundColor: "rgba(189, 189, 189, 0.24)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
    alignItems: "center",
  },
  closeButton: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 50,
    ...(Platform.OS === "web" ? { cursor: "pointer" } : {}),
  },
  headerText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 6,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  subHeaderText: {
    fontSize: 14.5,
    color: "#FFFFFF",
    opacity: 0.9,
    marginBottom: 22,
    textAlign: "center",
  },
  inputContainer: {
    width: "100%",
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 16,
    paddingHorizontal: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "transparent",
  },
  inputContainerFocused: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    borderColor: "rgba(255, 255, 255, 0.70)",
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 15,
    height: "100%",
    paddingVertical: 0,
  },
  eyeButton: {
    padding: 6,
    marginLeft: 4,
  },
  button: {
 backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 8,
  width: "100%",
  height: 52,
  borderRadius: 16,
  justifyContent: "center",
  alignItems: "center",
  marginTop: 6,
},
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "#000000ff",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginVertical: 18,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.35)",
  },
  dividerText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "700",
    marginHorizontal: 10,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  googleButton: {
    width: "100%",
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.42)",

    borderRadius: 16,
  },
  googleIcon: {
    width: 20,
    height: 20,
    marginRight: 10,
  },
  googleButtonText: {
    color: "#ffffffff",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 18,
    marginBottom: 0,
    paddingVertical: 2,
  },
  footerText: {
    color: "#FFFFFF",
    opacity: 0.9,
    fontSize: 14,
  },
  footerLink: {
    color: "#FFFFFF",
    fontSize: 14.5,
    fontWeight: "800",
    marginLeft: 6,
    textDecorationLine: "underline",
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  passwordRequirements: {
    width: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.56)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
    alignItems: "flex-start",
  },
  requirementsTitle: {
    fontSize: 11.5,
    fontWeight: "800",
    color: "#FFFFFF",
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  requirementItem: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 2.5,
  },
  requirementText: {
    fontSize: 12.5,
    marginLeft: 7,
    fontWeight: "600",
  },
  flex1: {
    flex: 1,
  },
  faceContainer: {
    width: "100%",
    alignItems: "center",
  },
  faceVisible: {
    width: "100%",
  },
  faceHidden: {
    position: "absolute",
    top: 24,
    left: 24,
    right: 24,
    opacity: 0,
  },
  backgroundWrapper: {
    ...StyleSheet.absoluteFillObject,
  },
});