import { StyleSheet, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
  },
  containerLight: {
    backgroundColor: "#FFFFFF",
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 16,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  backButtonLight: {
    backgroundColor: "rgba(0, 0, 0, 0.04)",
  },
  headerInfo: {
    flex: 1,
    marginRight: 12,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  titleMenuButton: {
    marginLeft: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  titleMenuButtonLight: {
    backgroundColor: "rgba(0, 0, 0, 0.05)",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: -0.4,
  },
  headerTitleLight: {
    color: "#000000",
  },
  headerSubtitle: {
    fontSize: 13,
    color: "#8E8E93",
    marginTop: 2,
    fontWeight: "500",
  },
  headerSubtitleLight: {
    color: "#666666",
  },
  gridContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 40,
  },
  gridItem: {
    overflow: "hidden",
    backgroundColor: "#161616",
  },
  gridItemLight: {
    backgroundColor: "#F0F0F0",
  },
  gridImage: {
    width: "100%",
    height: "100%",
  },
  modalOverlay: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.88)",
  },
  modalOverlayLight: {
    backgroundColor: "rgba(255, 255, 255, 0.90)",
  },
  modalCloseButton: {
    position: "absolute",
    top: 24,
    right: 24,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#2C2C2E",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 50,
  },
  modalCloseButtonLight: {
    backgroundColor: "#E5E5EA",
  },
  modalDeleteButton: {
    position: "absolute",
    bottom: 34,
    right: 20,
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#2C2C2E",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 30,
  },
  modalDeleteButtonLight: {
    backgroundColor: "#E5E5EA",
  },
  webViewerContainer: {
    flex: 1,
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  webModalImage: {
    width: "90%",
    height: "82%",
    maxWidth: 1200,
    maxHeight: 850,
  },
  webNavButton: {
    position: "absolute",
    top: "50%",
    marginTop: -25,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 25,
  },
  webNavButtonLight: {
    backgroundColor: "rgba(255, 255, 255, 0.8)",
  },
  webNavButtonLeft: {
    left: 24,
  },
  webNavButtonRight: {
    right: 24,
  },
  modalSlide: {
    width: SCREEN_WIDTH,
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  modalImage: {
    width: SCREEN_WIDTH,
    height: "100%",
  },
  captionPill: {
    position: "absolute",
    bottom: 34,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: "#2C2C2E",
    maxWidth: SCREEN_WIDTH - 130,
    zIndex: 20,
  },
  captionPillLight: {
    backgroundColor: "#E5E5EA",
  },
  menuBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
  },
  menuDropdown: {
    position: "absolute",
    top: 68,
    left: 16,
    width: 175,
    backgroundColor: "#1C1C1E",
    borderRadius: 14,
    paddingVertical: 5,
    paddingHorizontal: 4,
    borderWidth: 0,
    borderColor: "transparent",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 16,
    elevation: 12,
    zIndex: 100,
  },
  menuDropdownLight: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.08)",
    shadowColor: "#000",
    shadowOpacity: 0.15,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  menuItemIcon: {
    marginRight: 10,
  },
  menuItemText: {
    fontSize: 13.5,
    fontWeight: "500",
    color: "#FFFFFF",
    letterSpacing: -0.2,
  },
  menuItemTextLight: {
    color: "#000000",
  },
  menuItemTextDanger: {
    color: "#FF453A",
  },
  menuDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(255, 255, 255, 0.10)",
    marginHorizontal: 10,
  },
  menuDividerLight: {
    backgroundColor: "rgba(0, 0, 0, 0.08)",
  },
  captionPillText: {
    fontFamily: "Caveat-Bold",
    fontSize: 17,
    color: "#FFFFFF",
    paddingRight: 6,
    paddingLeft: 2,
  },
  captionPillTextLight: {
    color: "#000000",
  },
  editDialogOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  editDialogBox: {
    width: "100%",
    maxWidth: 320,
    borderRadius: 22,
    padding: 24,
    backgroundColor: "#000000",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 10,
  },
  editDialogBoxLight: {
    backgroundColor: "#FFFFFF",
    borderWidth: 0,
    borderColor: "transparent",
    shadowOpacity: 0.15,
  },
  editDialogTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 6,
  },
  editDialogTitleLight: {
    color: "#000000",
  },
  editDialogSubtitle: {
    fontSize: 13,
    color: "#D8D8DC",
    textAlign: "center",
    marginBottom: 18,
    lineHeight: 18,
  },
  editDialogSubtitleLight: {
    color: "#666666",
  },
  editDialogInput: {
    height: 50,
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 16,
    backgroundColor: "#111111",
    color: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  editDialogInputLight: {
    backgroundColor: "#F2F2F7",
    color: "#000000",
    borderColor: "transparent",
  },
  editDialogInputFocused: {
    borderColor: "#FFFFFF",
  },
  editDialogInputFocusedLight: {
    borderColor: "#000000",
  },
  charCountRow: {
    alignItems: "flex-end",
    marginTop: 6,
    marginRight: 4,
  },
  charCountText: {
    fontSize: 12,
    color: "#8E8E93",
    fontWeight: "500",
  },
  charCountTextLight: {
    color: "#8E8E93",
  },
  editDialogButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginTop: 18,
    gap: 10,
  },
  editDialogCancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  editDialogCancelText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#8E8E93",
  },
  editDialogSaveBtn: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
  },
  editDialogSaveBtnLight: {
    backgroundColor: "#000000",
  },
  editDialogSaveText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#000000",
  },
  editDialogSaveTextLight: {
    color: "#FFFFFF",
  },
  collectionModalCard: {
    width: "100%",
    maxWidth: 360,
    borderRadius: 22,
    padding: 22,
    backgroundColor: "#161616",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 10,
  },
  collectionModalCardLight: {
    backgroundColor: "#FFFFFF",
    shadowOpacity: 0.15,
  },
  collectionModalTitle: {
    fontSize: 19,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  collectionModalTitleLight: {
    color: "#000000",
  },
  collectionModalSubtitle: {
    fontSize: 13,
    color: "#8E8E93",
    marginBottom: 18,
    lineHeight: 18,
  },
  collectionModalSubtitleLight: {
    color: "#666666",
  },
  collectionModalSectionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 8,
  },
  collectionModalSectionLabelLight: {
    color: "#000000",
  },
  uploadPhotoBox: {
    borderRadius: 16,
    paddingVertical: 26,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "rgba(255, 255, 255, 0.25)",
  },
  uploadPhotoBoxLight: {
    backgroundColor: "rgba(0, 0, 0, 0.02)",
    borderColor: "rgba(0, 0, 0, 0.20)",
  },
  uploadPhotoIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255, 255, 255, 0.10)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  uploadPhotoIconCircleLight: {
    backgroundColor: "rgba(0, 0, 0, 0.06)",
  },
  uploadPhotoTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 3,
  },
  uploadPhotoTitleLight: {
    color: "#000000",
  },
  uploadPhotoSubtitle: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.5)",
  },
  uploadPhotoSubtitleLight: {
    color: "rgba(0, 0, 0, 0.5)",
  },
  modalActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 22,
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  modalCancelButtonLight: {
    backgroundColor: "rgba(0, 0, 0, 0.06)",
  },
  modalCancelButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  modalCancelButtonTextLight: {
    color: "#000000",
  },
  modalSubmitButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  modalSubmitButtonLight: {
    backgroundColor: "#000000",
  },
  modalSubmitButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#000000",
  },
  modalSubmitButtonTextLight: {
    color: "#FFFFFF",
  },
  editPhotosHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    marginBottom: 8,
  },
  editPhotosCountText: {
    fontSize: 12,
    color: "#8E8E93",
    fontWeight: "500",
  },
  editPhotosScrollContent: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  editPhotoThumbnailWrapper: {
    position: "relative",
    width: 72,
    height: 72,
    borderRadius: 12,
    overflow: "visible",
  },
  editPhotoThumbnail: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: "#2C2C2E",
  },
  editPhotoThumbnailLight: {
    backgroundColor: "#E5E5EA",
  },
  editPhotoDeleteBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#FF453A",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 4,
    elevation: 5,
  },
  emptyPhotosBox: {
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
  },
  emptyPhotosBoxLight: {
    backgroundColor: "rgba(0, 0, 0, 0.03)",
  },
  emptyPhotosText: {
    fontSize: 13,
    color: "#8E8E93",
    fontWeight: "500",
  },
  confirmOverlay: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 30,
  },
  confirmCard: {
    width: "100%",
    maxWidth: 275,
    backgroundColor: "#000000",
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 0,
    borderColor: "transparent",
  },
  confirmCardLight: {
    backgroundColor: "#FFFFFF",
    borderWidth: 0,
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  confirmContentSection: {
    paddingTop: 24,
    paddingBottom: 20,
    paddingHorizontal: 22,
    alignItems: "center",
  },
  confirmTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 8,
  },
  confirmTitleLight: {
    color: "#000000",
  },
  confirmMessage: {
    fontSize: 13.5,
    color: "#E5E5E5",
    textAlign: "center",
    lineHeight: 19,
  },
  confirmMessageLight: {
    color: "#555555",
  },
  confirmBoldText: {
    fontWeight: "700",
    color: "#FFFFFF",
  },
  confirmBoldTextLight: {
    color: "#000000",
  },
  confirmActionButton: {
    width: "100%",
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255, 255, 255, 0.1)",
    backgroundColor: "transparent",
  },
  confirmActionButtonLight: {
    borderTopColor: "rgba(0, 0, 0, 0.08)",
  },
  confirmLastButton: {
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
  },
  confirmDeleteText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FF3B30",
  },
  confirmCancelText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  confirmCancelTextLight: {
    color: "#000000",
  },
  bottomTranslucentBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 96,
    backgroundColor: "rgba(0, 0, 0, 0.52)",
    zIndex: 15,
  },
  bottomTranslucentBarLight: {
    backgroundColor: "rgba(255, 255, 255, 0.70)",
  },
});
